services:
  dev-box:
    build: .
    image: dev-box
    container_name: dev-box
    ports:
      - "40022:2222"
      - "48080:8080"
      - "9095:9095"
    stdin_open: true
    tty: true
    volumes:
      - ./data:/data
      - ./ssh:/home/user/.ssh
      - ./.p10k.zsh:/home/user/.p10k.zsh   # p10k 새로 설정하려면 이 줄 제거 후 컨테이너에서 `p10k configure`
    # GPU 호스트면 아래 주석 해제
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [gpu]
    #            #device_ids: ['0','2']
    #            # runtime: nvidia
